server:
  port: 8081
spring:
  application:
    name: order-service
#  profiles:
#    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888



#server:
#  port: 8081
###eureka:
###  client:
###    serviceUrl:
###      defaultZone: http://localhost:8761/eureka
##
### mongoDB
### Database configuration
#spring:
#  application:
#    name: order-service
#  profiles:
#    active: dev
#
#  cloud:
#    config:
#     enabled: false
#
#     # uri: http://localhost:8083
#
##  cloud:
##    config:
##      uri: http://localhost:8083
##  #  data:
##  #    mongodb:
##  #      uri : mongodb://localhost:27017/
##  #      database : mongoDB-dev
##
##  # Profiling in Spring Boot
##
###
#  config:
#    import: optional:configserver:http://localhost:8083
##
### H2 Database configuration
###spring:
###  application:
###    name: order-service
###  datasource:
###    url: jdbc:h2:mem:mydb
###    username: sa
###    password: password
###    driverClassName: org.h2.Driver
###  jpa:
###    database-platform: org.hibernate.dialect.H2Dialect
##
###logging:
##logging:
##  file.name: C:/Users/ramlal.dhangar/Training-Project/application-Logs/order-service.log
